POST http://localhost:3003/users/signup
Content-Type: application/json

{
    "email": "renata_vieira@hotmail.com",
    "name": "Renata Vieira",
    "password": "123456",
    "role": "NORMAL"
}


###
POST http://localhost:3003/users/login
Content-Type: application/json

{
    "email": "joaopedro.dallagnol@gmail.com",
    "password": "123456"
}


###
DELETE http://localhost:3003/users/sf563-kufq7A-H56k8-qw86a-se6f44-gjl5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBmN2ZhY2NjLWQ0YjAtNDE2Mi1hMzBkLWVkZDBiM2UyZmMyYSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY3NjUwNTI5NiwiZXhwIjoxNjc2NTA4ODk2fQ.dw-YCbpJWpURerjNQYqmWicfbmiWxvf9o4LqsmQmzaA
Content-Type: application/json


###
GET http://localhost:3003/users/account
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJhYzA5NWIxLTc3NmYtNDFkNC05NDM1LTVhMmNmZDEwZmM2MiIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NzYzMzAzNDgsImV4cCI6MTY3NjMzMzk0OH0._9t7J-N_Tz43p2Gzp_sHc0P_iOJDG9jOeiSysLAtAlY
Content-Type: application/json


###
GET http://localhost:3003/users/sf563-kufq7A-H56k8-qw86a-se6f44-gjl5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJhYzA5NWIxLTc3NmYtNDFkNC05NDM1LTVhMmNmZDEwZmM2MiIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NzY0MTQ5NzMsImV4cCI6MTY3NjQxODU3M30.cV5r8Oiq0iLzfGJf6rVAG2SMIVB0TGlXFBNie-i0g7c
Content-Type: application/json


###
POST http://localhost:3003/users/follow
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJhYzA5NWIxLTc3NmYtNDFkNC05NDM1LTVhMmNmZDEwZmM2MiIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NzY0MTczMTQsImV4cCI6MTY3NjQyMDkxNH0.3__Ktmx6JBNqni9zEqecJsPKJg-r-b6gzgaQozQSK5Y
Content-Type: application/json

{
    "userId": "987DF-500Zg5A-8gud9-ssds-k65ZSA-HS5A"
}


###
POST http://localhost:3003/users/unfollow
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJhYzA5NWIxLTc3NmYtNDFkNC05NDM1LTVhMmNmZDEwZmM2MiIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NzY0MTczMTQsImV4cCI6MTY3NjQyMDkxNH0.3__Ktmx6JBNqni9zEqecJsPKJg-r-b6gzgaQozQSK5Y
Content-Type: application/json

{
    "userId": "987DF-500Zg5A-8gud9-ssds-k65ZSA-HS5A"
}


###
DELETE http://localhost:3003/recipes/7
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBmN2ZhY2NjLWQ0YjAtNDE2Mi1hMzBkLWVkZDBiM2UyZmMyYSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY3NjUwMTQ3NiwiZXhwIjoxNjc2NTA1MDc2fQ.L_EVnVMd_a893Tb-ks3cBWI26XdretrFb5K8PZKX_8g
Content-Type: application/json


###
POST http://localhost:3003/recipes/create
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJhYzA5NWIxLTc3NmYtNDFkNC05NDM1LTVhMmNmZDEwZmM2MiIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NzY1MDAyMTIsImV4cCI6MTY3NjUwMzgxMn0.fH5N11TkVtLUwvm4WAuNVvU8xwFQR-8baNxLu2EtdoM
Content-Type: application/json

{
    "title": "teste",
    "description": "descrição teste"
}


###
PUT http://localhost:3003/recipes/6
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJhYzA5NWIxLTc3NmYtNDFkNC05NDM1LTVhMmNmZDEwZmM2MiIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NzY1MDAyMTIsImV4cCI6MTY3NjUwMzgxMn0.fH5N11TkVtLUwvm4WAuNVvU8xwFQR-8baNxLu2EtdoM
Content-Type: application/json

{
    "title": "teste3",
    "description": "descrição 2"
}

###
GET http://localhost:3003/recipes
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJhYzA5NWIxLTc3NmYtNDFkNC05NDM1LTVhMmNmZDEwZmM2MiIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NzYzMzU2MzQsImV4cCI6MTY3NjMzOTIzNH0.i-iV_D66eRv-w2r0c4yGmJo7sxvcs8fQHbbxk4iCD-o
Content-Type: application/json


###
GET http://localhost:3003/recipes/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJhYzA5NWIxLTc3NmYtNDFkNC05NDM1LTVhMmNmZDEwZmM2MiIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NzY0MTYzMTMsImV4cCI6MTY3NjQxOTkxM30.8UT57VuKUCQVtqARp4v6OjFn8y0upwpcSHo-AKWyIW0
Content-Type: application/json