POST http://localhost:3003/users/signup
Content-Type: application/json

{
    "email": "mari_boeira@gmail.com",
    "name": "Mariana Boeira",
    "password": "123456",
    "role": "NORMAL"
}


###
POST http://localhost:3003/users/login
Content-Type: application/json

{
    "email": "mari_boeira@gmail.com",
    "password": "123456"
}


###
GET http://localhost:3003/users/account
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJhYzA5NWIxLTc3NmYtNDFkNC05NDM1LTVhMmNmZDEwZmM2MiIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NzYzMzAzNDgsImV4cCI6MTY3NjMzMzk0OH0._9t7J-N_Tz43p2Gzp_sHc0P_iOJDG9jOeiSysLAtAlY
Content-Type: application/json


###
GET http://localhost:3003/users/sf563-kufq7A-H56k8-qw86a-se6f44-gjl5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJhYzA5NWIxLTc3NmYtNDFkNC05NDM1LTVhMmNmZDEwZmM2MiIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NzY0MTQ5NzMsImV4cCI6MTY3NjQxODU3M30.cV5r8Oiq0iLzfGJf6rVAG2SMIVB0TGlXFBNie-i0g7c
Content-Type: application/json


###
POST http://localhost:3003/recipes/create
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJhYzA5NWIxLTc3NmYtNDFkNC05NDM1LTVhMmNmZDEwZmM2MiIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NzYzMzAzNDgsImV4cCI6MTY3NjMzMzk0OH0._9t7J-N_Tz43p2Gzp_sHc0P_iOJDG9jOeiSysLAtAlY
Content-Type: application/json

{
    "title": "teste",
    "description": "descrição teste"
}


###
POST http://localhost:3003/users/sd4iu-6r84cd-askjbdaj-564sd46ad-kjsd
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJhYzA5NWIxLTc3NmYtNDFkNC05NDM1LTVhMmNmZDEwZmM2MiIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NzYzMzAzNDgsImV4cCI6MTY3NjMzMzk0OH0._9t7J-N_Tz43p2Gzp_sHc0P_iOJDG9jOeiSysLAtAlY
Content-Type: application/json


###
GET http://localhost:3003/recipes
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJhYzA5NWIxLTc3NmYtNDFkNC05NDM1LTVhMmNmZDEwZmM2MiIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NzYzMzU2MzQsImV4cCI6MTY3NjMzOTIzNH0.i-iV_D66eRv-w2r0c4yGmJo7sxvcs8fQHbbxk4iCD-o
Content-Type: application/json